### ISSUE TITLE
Why rest endpoints?

### ISSUE THREAD

**Issue by 4F2E4A2E** [adrien2p/nest-js-graphql#4]
Hello there! Thank you for this repo, but do i assume correctly, that those [1] are rest endpoints? Why are they built in?

1: https://github.com/adrien2p/nestjs-graphql/blob/f983bbe3bd5aafdbca9ab45a0171818bef8e11ae/src/modules/cars/cars.controller.ts

**Comment by adrien2p** [comment]
Hello you !

I’ve let the rest endpoints because just a part of the models are exposed through graphql (as example) so the graphql example implementation is part of the rest project, they live together :)

But if you want you can go to have only graphql implementation but it’s depend of you need but this two can live together.
